In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\vamsi\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vamsi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [8]:
df=pd.read_excel("C:/Users/vamsi/OneDrive/Documents/water consumption record with null.xlsx")

In [9]:
df

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
0,10001,2023-01-01,Chennai,463.0,5.0,1294.0
1,10002,2023-01-02,Mumbai,NaN,NaN,1627.0
2,10003,2023-01-03,Bengaluru,NaN,2.0,1785.0
3,10004,2023-01-04,Mumbai,319.0,5.0,2014.0
4,10005,2023-01-05,Mumbai,120.0,6.0,1620.0
...,...,...,...,...,...,...
4995,14996,2036-09-04,Chennai,NaN,2.0,2055.0
4996,14997,2036-09-05,Chennai,130.0,6.0,2087.0
4997,14998,2036-09-06,Mumbai,59.0,5.0,879.0
4998,14999,2036-09-07,Chennai,57.0,4.0,2035.0
4999,15000,2036-09-08,Mumbai,454.0,2.0,2377.0

In [10]:
df.head()

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
0,10001,2023-01-01,Chennai,463.0,5.0,1294.0
1,10002,2023-01-02,Mumbai,NaN,NaN,1627.0
2,10003,2023-01-03,Bengaluru,NaN,2.0,1785.0
3,10004,2023-01-04,Mumbai,319.0,5.0,2014.0
4,10005,2023-01-05,Mumbai,120.0,6.0,1620.0

In [11]:
df.tail()

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
4995,14996,2036-09-04,Chennai,NaN,2.0,2055.0
4996,14997,2036-09-05,Chennai,130.0,6.0,2087.0
4997,14998,2036-09-06,Mumbai,59.0,5.0,879.0
4998,14999,2036-09-07,Chennai,57.0,4.0,2035.0
4999,15000,2036-09-08,Mumbai,454.0,2.0,2377.0

In [12]:
# finding data structure

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               5000 non-null   int64
 1   Date                      5000 non-null   datetime64[ns]
 2   City                      4500 non-null   object
 3   Water_Consumption_Liters  4500 non-null   float64
 4   Household_Size            4500 non-null   float64
 5   Water_Bill_Amount         4500 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 234.5+ KB

In [14]:
df.dtypes

Customer_ID                          int64
Date                        datetime64[ns]
City                                object
Water_Consumption_Liters           float64
Household_Size                     float64
Water_Bill_Amount                  float64
dtype: object

In [15]:
df.shape

(5000, 6)

In [16]:
# checking null values

In [17]:
df.isnull()

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
0,False,False,False,False,False,False
1,False,False,False,True,True,False
2,False,False,False,True,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
4995,False,False,False,True,False,False
4996,False,False,False,False,False,False
4997,False,False,False,False,False,False
4998,False,False,False,False,False,False
4999,False,False,False,False,False,False

In [18]:
df.isnull().sum()

Customer_ID                   0
Date                          0
City                        500
Water_Consumption_Liters    500
Household_Size              500
Water_Bill_Amount           500
dtype: int64

In [19]:
# check row wise null values

In [20]:
df[df.isnull().any(axis=1)]

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
1,10002,2023-01-02,Mumbai,NaN,NaN,1627.0
2,10003,2023-01-03,Bengaluru,NaN,2.0,1785.0
5,10006,2023-01-06,Vijayawada,229.0,NaN,536.0
12,10013,2023-01-13,Mumbai,277.0,5.0,NaN
13,10014,2023-01-14,Vijayawada,480.0,NaN,374.0
...,...,...,...,...,...,...
4986,14987,2036-08-26,Mumbai,446.0,6.0,NaN
4989,14990,2036-08-29,Mumbai,333.0,3.0,NaN
4992,14993,2036-09-01,NaN,366.0,3.0,1938.0
4993,14994,2036-09-02,Mumbai,172.0,NaN,NaN
4995,14996,2036-09-04,Chennai,NaN,2.0,2055.0

In [21]:
# NOTE:- Dataset contains  missing values, So filling or dropping was required.

In [22]:
# START CLEANING

In [23]:
# Fill City (Categorical) with MODE

In [24]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [27]:
# now check null values in city column is filled with values or not

In [28]:
df["City"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: City, Length: 5000, dtype: bool

In [29]:
# count null values are there in city column

In [30]:
df["City"].isnull().sum()

np.int64(0)

In [31]:
#  Fill Numeric Columns with MEAN

In [32]:
df["Water_Consumption_Liters"]=df["Water_Consumption_Liters"].fillna(df["Water_Consumption_Liters"].mean())

In [33]:
df["Water_Consumption_Liters"].isnull().sum()

np.int64(0)

In [34]:
df["Household_Size"]=df["Household_Size"].fillna(df["Household_Size"].mean())

In [35]:
df["Household_Size"].isnull().sum()

np.int64(0)

In [36]:
df["Water_Bill_Amount"]=df["Water_Bill_Amount"].fillna(df["Water_Bill_Amount"].mean())

In [37]:
df["Water_Bill_Amount"].isnull().sum()

np.int64(0)

In [38]:
# Now verify dataset is cleaned or null

In [39]:
df.isnull().sum()

Customer_ID                 0
Date                        0
City                        0
Water_Consumption_Liters    0
Household_Size              0
Water_Bill_Amount           0
dtype: int64

In [40]:
df

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
0,10001,2023-01-01,Chennai,463.000000,5.000000,1294.0
1,10002,2023-01-02,Mumbai,274.713333,4.013778,1627.0
2,10003,2023-01-03,Bengaluru,274.713333,2.000000,1785.0
3,10004,2023-01-04,Mumbai,319.000000,5.000000,2014.0
4,10005,2023-01-05,Mumbai,120.000000,6.000000,1620.0
...,...,...,...,...,...,...
4995,14996,2036-09-04,Chennai,274.713333,2.000000,2055.0
4996,14997,2036-09-05,Chennai,130.000000,6.000000,2087.0
4997,14998,2036-09-06,Mumbai,59.000000,5.000000,879.0
4998,14999,2036-09-07,Chennai,57.000000,4.000000,2035.0
4999,15000,2036-09-08,Mumbai,454.000000,2.000000,2377.0

In [41]:
# save cleaned data set

In [47]:
df.to_excel("C:/Users/vamsi/OneDrive/Documents/water consumption record with null.xlsx", index=False)

In [48]:
df

,Customer_ID,Date,City,Water_Consumption_Liters,Household_Size,Water_Bill_Amount
0,10001,2023-01-01,Chennai,463.000000,5.000000,1294.0
1,10002,2023-01-02,Mumbai,274.713333,4.013778,1627.0
2,10003,2023-01-03,Bengaluru,274.713333,2.000000,1785.0
3,10004,2023-01-04,Mumbai,319.000000,5.000000,2014.0
4,10005,2023-01-05,Mumbai,120.000000,6.000000,1620.0
...,...,...,...,...,...,...
4995,14996,2036-09-04,Chennai,274.713333,2.000000,2055.0
4996,14997,2036-09-05,Chennai,130.000000,6.000000,2087.0
4997,14998,2036-09-06,Mumbai,59.000000,5.000000,879.0
4998,14999,2036-09-07,Chennai,57.000000,4.000000,2035.0
4999,15000,2036-09-08,Mumbai,454.000000,2.000000,2377.0